language: cpp
dist: trusty
sudo: required

before_install:
  - . .travis.setup

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..

script:
  - make -j2 VERBOSE=1